services:
  web:
    image: nginx:stable-alpine
    container_name: mag_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/log:/var/log/nginx
    depends_on:
      - php
      - db

  php:
    build: .docker/php
    container_name: mag_php
    volumes:
      - .:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini

  db:
    image: mysql:8.0
    container_name: mag_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mag
      MYSQL_USER: mag
      MYSQL_PASSWORD: mag
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mag_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db